pipeline {
    agent any

    environment {
        // Define the name of the Docker image
        DOCKER_IMAGE = 'java-hello-world'
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image using the Dockerfile
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }

        stage('Run Java Application') {
            steps {
                script {
                    // Run the Docker container and execute the Java application
                    sh 'docker run --rm ${DOCKER_IMAGE}'
                }
            }
        }
    }

    post {
        always {
            // Clean up the Docker image after the build
            sh 'docker rmi ${DOCKER_IMAGE} || true'
        }
    }
}
